#! /bin/sh

bspc monitor DVI-1  -d vi vii viii ix x
bspc monitor HDMI-0 -d i ii iii iv v

bspc config border_width        3
bspc config window_gap          5
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config top_padding         15
bspc config focus_follows_pointer true

bspc config normal_border_color "#332d29"
bspc config active_border_color "#817267"
bspc config focused_border_color "#504339"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"

nitrogen --restore &

urxvtd &

# bash ${HOME}.config/bspwm/barPanel
${HOME}/.config/bspwm/panel &
