#! /bin/sh
#
# Example panel for LemonBoy's bar


source ~/.config/bspwm/panel.cfg

# Bright Zenburn-esque
COLOR1=#FFf0ebcd
COLOR2=#FF568090
COLOR3=#FFc08158

# ----- Summer ----- #
#COLOR2=#FF648ea7
#COLOR3=#FF91b6c6
# ----- PINK ----- #
#COLOR2=#FFf36b6b
#COLOR3=#FFff897d

# ----- Bliss ----- #
#COLOR2=#FF1369ee
#COLOR3=#FF6997ed

num_mon=$(bspc query -M | wc -l)

chg(){
	echo -n  $(acpi --battery | awk '{gsub(/,/, "");} {print $4}')
}

bat(){ 
	echo -n  $(acpi -a | if grep -q "on-line"; then echo -n ""; else echo -n "⭫ $(chg)%"; fi)
}

ram(){
	echo -n  $(free -m | awk '/Mem/ {print $3}')
}

dat(){
	echo -n  $(date "+%H:%M  %D")
}

vol(){
  volume=$(amixer sget Master | awk -F"[][]" '/dB/ { print $2 }')
  if [[ $volume == "0%" ]]; then
    echo -n "mute"
  else
    echo -n $volume
  fi
}

mus(){
	echo -n  $(test -z "$(mpc current)" || mpc current)
  # echo -n  $(test -z "$(mpc current)" || mpc current -f %title%)
	#echo -n $(ps aux | grep -v "grep" | if grep -q "cmus"; then echo $(cmus-remote -Q | sed -n 's/tag title //p'); else echo "n/a"; fi)
}

paws(){
	echo -n  $(mpc | if grep -q "paused"; then echo -n "▮▮"; else echo -n "♫"; fi)
	#echo -n $(cmus-remote -Q | if grep -q "paused"; then echo -n "▮▮"; else echo -n "♫"; fi)
}

while read -r line ; do
	case $line in
		S*)
			# clock output
			sys_infos="${line#?}"
			;;
		T*)
			# xtitle output
			title="${line#?}"
			;;
		I*)
			# wifi output
			wifi="${line#?}"
			;;
		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					M*)
						# active monitor
						if [ $num_mon -gt 1 ] ; then
              wm_infos="$wm_infos %{B-}%{F-}%{F$COLOR1}%{B$COLOR2}"
							wm_infos="$wm_infos %{F$ACTIVE_MONITOR_FG}%{B$COLOR2} ${name} %{B-}%{F-}"
              wm_infos="$wm_infos%{B-}%{F-}%{F$COLOR2}%{B$COLOR1}"
						fi
						;;
					m*)
						# inactive monitor
						if [ $num_mon -gt 1 ] ; then
              wm_infos="$wm_infos %{B-}%{F-}%{F$COLOR1}%{B$COLOR2}"
							wm_infos="$wm_infos %{F$ACTIVE_MONITOR_FG}%{B$COLOR2} ${name} %{B-}%{F-}"
              wm_infos="$wm_infos%{B-}%{F-}%{F$COLOR2}%{B$COLOR1}"
						fi
						;;
					O*)
						# focused occupied desktop
						wm_infos="${wm_infos}%{F$FOREGROUND}%{B$COLOR1}%{U$COLOR3}%{+u} ${name} %{-u}%{B-}%{F-}"
						;;
					F*)
						# focused free desktop
						wm_infos="${wm_infos}%{F$FOREGROUND}%{B$COLOR1}%{U$COLOR3}%{+u} ${name} %{-u}%{B-}%{F-}"
						;;
					U*)
						# focused urgent desktop
						wm_infos="${wm_infos}%{F$FOREGROUND}%{B$COLOR1}%{U$COLOR3}%{+u} ${name} %{-u}%{B-}%{F-}"
						;;
					o*)
						# occupied desktop
						wm_infos="${wm_infos}%{F$FOREGROUND}%{B$COLOR1}%{U$COLOR2}%{+u} ${name} %{-u}%{B-}%{F-}"
						;;
					f*)
						# free desktop
						wm_infos="${wm_infos}%{F$FOREGROUND}%{B$COLOR1}%{U$COLOR2}%{+u} ${name} %{-u}%{B-}%{F-}"
						;;
					u*)
						# urgent desktop
						wm_infos="${wm_infos}%{F$COLOR3}%{B$COLOR1}%{U$COLOR2}%{+u} ${name} %{-u}%{B-}%{F-}"
						;;
					L*)
						# layout
            # strip off last character
						wm_infos="${wm_infos%?} %{F$COLOR2}%{B$COLOR1}  %{B-}%{F-}"
						;;
				esac
				shift
			done
			;;
	esac

  # play or pause
  printf "%s" "%{Sl} %{A:mpc toggle:}%{B$COLOR2}%{F$COLOR1} $(paws) "

  # a separator
  printf "%s" "%{F$COLOR2}%{B$COLOR3}"

  # the current playing song
  printf "%s" "%{A}%{A:osd:}%{F-}%{B-}%{F$COLOR1}%{B$COLOR3} $(mus) "

  # separator
  printf "%s" "%{B-}%{A}%{B$COLOR1}%{F$COLOR3}"

  # window information (centered)
  printf "%s" "%{B-}%{F-}%{B$COLOR1}%{c} $wm_infos"
  
  # separators
  printf "%s" "%{B-}%{c}%{r}%{F$COLOR2}"
  printf "%s" "%{B-}%{F$COLOR3}"

  # ram
  printf "%s" "%{F-}%{B$COLOR3}%{F$COLOR1} ram $(ram) vol $(vol) "

  # separator
  printf "%s" "%{F-}%{F$COLOR2}%{B$COLOR3}"

  # date
  printf "%s" "%{F-}%{B-}%{B$COLOR2}%{F$COLOR1} $(dat)"

  # end
  printf "%s\n" "%{B-}%{F-}"

	#printf "%s\n" "%{Sl} %{l} %{F#FF${BLUE}} ⮗ $title %{c} $wm_infos  %{r} $wifi %{F#FF${YELLOW}} $sys_infos"


  #printf "%s\n" "%{Sl} %{A:mpc toggle:}%{B$COLOR2} %{F$COLOR1}$(paws)
  #%{F$COLOR2}%{B$COLOR3}%{A}%{A:osd:}%{F-}%{B-}%{F$COLOR1}%{B$COLOR3} $(mus)
  #%{B-}%{A}%{c}%{B$COLOR2}%{F$COLOR1} %{B-}%{F-}%{B$COLOR2} %%{c}$wm_infos
  #%{B-}%{F-}%{F$COLOR1}%{B$COLOR2}%{B-}%{F-}%{c}%{r}%{F$COLOR3}%{F-}%{B$COLOR3}%{F$COLOR1}
  #ram $(ram) vol $(vol)%
  #%{B-}%{F-}%{F$COLOR2}%{B$COLOR3}%{F-}%{B-}%{B$COLOR2}%{F$COLOR1} $(dat)
  #%{B-}%{F-}" 
done
